config/routes.rb
Parsingtool::Application.routes.draw do
  resources :services
  root 'services#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :service

  validates :title, presence: true
  validates_uniqueness_of :title, scope: :service_id
  validates :text, presence: true
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :snippets, dependent: :destroy
  has_many :articles, dependent: :destroy

  before_save :make_short_upcase

  validates :name, uniqueness: true, presence: true
  validates :short, uniqueness: true, presence: true

  private

  def make_short_upcase
    self.short = self.short.upcase
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :service

  validates :name, presence: true
  validates_uniqueness_of :name, scope: :service_id
  validates :source, presence: true

  def parse(content)
    return self.source % content
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.includes(:articles, :snippets).find(params[:id])
    @articles = @service.articles.order(created_at: :desc).limit(20)
    @snippets = @service.snippets.order(:name)
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if(@service.save)
      redirect_to service_path(@service)
    else
      redirect_to services_path, flash: @service.errors
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(params[:service].permit(:name, :short))
      redirect_to service_path(@service)
    else
      redirect_to edit_service_path(@service),
        flash: "Konnte nicht geändert werden."
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    redirect_to services_path
  end

  private

  def service_params
    params.require(:service).permit(:name, :short)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parsingtool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :short %>
  <%= f.text_field :short %>
  <%= f.submit %>
<% end %>

app/views/services/edit.html.erb
<h1><%= @service.name %> editieren.</h1>

<%= render "form" %>

app/views/services/index.html.erb
<h1>Übersicht aller Dienste</h1>

<ul>
  <% @services.each do |service| %>
    <li><%= link_to "#{ service.name } (#{ service.short })", service %></li>
  <% end %>
</ul>

<%= link_to "Neuen Dienst erstellen", new_service_path %>

app/views/services/new.html.erb
<h1>Neuen Dienst einrichten</h1>

<%= render "form" %>

<%= link_to "zurück zur Übersicht", services_path %>

app/views/services/show.html.erb
<h1><%= @service.short %> - <%= @service.name %></h1>

<p>
  <%= link_to "ändern", edit_service_path(@service) %>
  <%= link_to "löschen",
              service_path(@service),
              method: :delete,
              data: {
                confirm: "Wollen Sie wirklich #{ @service.name } löschen?"
              } %>
</p>

<% if @articles.empty? %>
  <h2>Keine Artikel vorhanden.</h2>
<% else %>
  <h2>Artikel</h2>
<% end %>
<ul>
  <% @articles.each do |article| %>
    <li><%= article.created_at.strftime("%d.%m.%Y") %> - <%= article.title %></li>
  <% end %>
</ul>

<% if @snippets.empty? %>
  <h2>Keine Snippets vorhanden.</h2>
<% else %>
  <h2>Snippets</h2>
<% end %>
<ul>
  <% @snippets.each do |snippet| %>
    <li><%= snippet.name %></li>
  <% end %>
</ul>

<%= link_to "Übersicht", services_path %>